using System;
using System.Collections;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.Xml.Linq;
using Shelf.Support.Searching;
using Shelf.Support;
using Shelf.Support.Indexing;
using Shelf.Support.Logging;

namespace Shelf.Web
{
    public partial class CrawlingAspx : System.Web.UI.Page
    {
        /// <summary>Store the catalog while we look at it</summary>
        private Catalog _Catalog;

        /// <summary>
        /// Event level to log (to the Html output)
        /// Values 1(show only necessary msgs) to 5 (show all progress msgs)
        /// Higher the value , more verbose are the feedback messages..
        /// </summary>
        private int _ProgressEventLevel = Preferences.IndexerDefaultVerbosity;

        /// <summary>
        /// This page uses the Spider class to read and catalog a website
        /// </summary>
        protected void Page_Load(object sender, EventArgs e)
        {
            Response.Write(
                          @"<html>
                            <head>
		                        <style type='text/css'>
			                        BODY { color: #000000; background-color: white; font-family: trebuchet ms, verdana, arial, sans-serif; font-size:x-small; margin-left: 0px; margin-top: 0px; }
		                        </style>
		                        <title>Crawling the library...</title>
                            </head>
                            <body>
                            <h3><p><font color='red'>S</font><font color='blue'>h</font><font color='green'>e</font><font color='orange'>l</font><font color='navy'>f</font>.<font color='maroon'>Search</font> <font color='#990000'><sup>Beta</sup></font></p></h3>
                            <h2>Catalog file not found! Building Catalog now ..</h2><p>"
                          );
            // Build the catalog!
            Spider spidey = new Spider();
            spidey.SpiderProgressEvent += new SpiderProgressEventHandler(OnProgressEvent);
            _Catalog = spidey.BuildCatalog();
            Cache[Preferences.CatalogCacheKey] = _Catalog;

            // Check if anything was found
            if (_Catalog.Length > 0)
            {
                Response.Write("<br />Finished - now you can search!</p>");
                Logger.PerformanceLog(this, "Built new Catalog successfully!");
                Response.Write("<center><a href='Search.aspx'><h3>Start Searching Now !</a></h3></center>");
                Response.Write("</body></html>");
                
            }
            else
            {
                Response.Write("</p><br /><p font='color:red'>Sorry, nothing was cataloged." +
                    " Administrator will check if there are resources to catalog," +
                    " and the logs to see if any error has occured. Sorry for the " +
                    "inconvenience, please check back here later.</p>");
                Response.Write("</body></html>");
                Response.End();
            }
        } // Page_Load

        /// <summary>
        /// Handle events generated by the Spider (mostly reporting on success/failure of documents loading/indexing)
        /// </summary>
        public void OnProgressEvent(object source, ProgressEventArgs pea)
        {
            //Define the actions to be performed on
            //button click here.
            if (pea.Level < _ProgressEventLevel)
            {
                Response.Write(pea.Level + " :: " + pea.Message + "<br />");
                Response.Flush();
            }
        }
    }
}
