//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IDaybookClientService", Namespace="http://tempuri.org/")]
public partial class DaybookClientService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback PingServiceOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetContactsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetScheduledEventsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetTasksOperationCompleted;
    
    /// <remarks/>
    public DaybookClientService() {
        string urlSetting = System.Configuration.ConfigurationManager.AppSettings["DaybookClientServiceAddress"];
        if ((urlSetting != null))
        {
            this.Url = urlSetting;
        }
        else
        {
            this.Url = "http://localhost:49299/AuthWCF/Services/DaybookClientService.svc";
        } 
        
    }
    
    /// <remarks/>
    public event PingServiceCompletedEventHandler PingServiceCompleted;
    
    /// <remarks/>
    public event GetContactsCompletedEventHandler GetContactsCompleted;
    
    /// <remarks/>
    public event GetScheduledEventsCompletedEventHandler GetScheduledEventsCompleted;
    
    /// <remarks/>
    public event GetTasksCompletedEventHandler GetTasksCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDaybookClientService/PingService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool PingService() {
        object[] results = this.Invoke("PingService", new object[0]);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPingService(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PingService", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndPingService(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void PingServiceAsync() {
        this.PingServiceAsync(null);
    }
    
    /// <remarks/>
    public void PingServiceAsync(object userState) {
        if ((this.PingServiceOperationCompleted == null)) {
            this.PingServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingServiceOperationCompleted);
        }
        this.InvokeAsync("PingService", new object[0], this.PingServiceOperationCompleted, userState);
    }
    
    private void OnPingServiceOperationCompleted(object arg) {
        if ((this.PingServiceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PingServiceCompleted(this, new PingServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDaybookClientService/GetContacts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Contact[] GetContacts() {
        object[] results = this.Invoke("GetContacts", new object[0]);
        return ((Contact[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetContacts(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetContacts", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public Contact[] EndGetContacts(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Contact[])(results[0]));
    }
    
    /// <remarks/>
    public void GetContactsAsync() {
        this.GetContactsAsync(null);
    }
    
    /// <remarks/>
    public void GetContactsAsync(object userState) {
        if ((this.GetContactsOperationCompleted == null)) {
            this.GetContactsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContactsOperationCompleted);
        }
        this.InvokeAsync("GetContacts", new object[0], this.GetContactsOperationCompleted, userState);
    }
    
    private void OnGetContactsOperationCompleted(object arg) {
        if ((this.GetContactsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetContactsCompleted(this, new GetContactsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDaybookClientService/GetScheduledEvents", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public ScheduledEvent[] GetScheduledEvents() {
        object[] results = this.Invoke("GetScheduledEvents", new object[0]);
        return ((ScheduledEvent[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetScheduledEvents(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetScheduledEvents", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ScheduledEvent[] EndGetScheduledEvents(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ScheduledEvent[])(results[0]));
    }
    
    /// <remarks/>
    public void GetScheduledEventsAsync() {
        this.GetScheduledEventsAsync(null);
    }
    
    /// <remarks/>
    public void GetScheduledEventsAsync(object userState) {
        if ((this.GetScheduledEventsOperationCompleted == null)) {
            this.GetScheduledEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetScheduledEventsOperationCompleted);
        }
        this.InvokeAsync("GetScheduledEvents", new object[0], this.GetScheduledEventsOperationCompleted, userState);
    }
    
    private void OnGetScheduledEventsOperationCompleted(object arg) {
        if ((this.GetScheduledEventsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetScheduledEventsCompleted(this, new GetScheduledEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDaybookClientService/GetTasks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Task[] GetTasks() {
        object[] results = this.Invoke("GetTasks", new object[0]);
        return ((Task[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetTasks(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetTasks", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public Task[] EndGetTasks(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Task[])(results[0]));
    }
    
    /// <remarks/>
    public void GetTasksAsync() {
        this.GetTasksAsync(null);
    }
    
    /// <remarks/>
    public void GetTasksAsync(object userState) {
        if ((this.GetTasksOperationCompleted == null)) {
            this.GetTasksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTasksOperationCompleted);
        }
        this.InvokeAsync("GetTasks", new object[0], this.GetTasksOperationCompleted, userState);
    }
    
    private void OnGetTasksOperationCompleted(object arg) {
        if ((this.GetTasksCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetTasksCompleted(this, new GetTasksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Contact {
    
    private string contactNameField;
    
    private string contactMobileField;
    
    private string contactPhoneNumberField;
    
    private string contactEmailField;
    
    private string tagsField;
    
    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    public string ContactMobile {
        get {
            return this.contactMobileField;
        }
        set {
            this.contactMobileField = value;
        }
    }
    
    /// <remarks/>
    public string ContactPhoneNumber {
        get {
            return this.contactPhoneNumberField;
        }
        set {
            this.contactPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ContactEmail {
        get {
            return this.contactEmailField;
        }
        set {
            this.contactEmailField = value;
        }
    }
    
    /// <remarks/>
    public string Tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Task {
    
    private string taskNameField;
    
    private string descriptionField;
    
    private string repositoryField;
    
    private string targetGroupOrUserField;
    
    private string createdUserField;
    
    private System.DateTime startTimeField;
    
    private System.DateTime dueDateField;
    
    private short priorityField;
    
    private string percentageCompleteField;
    
    /// <remarks/>
    public string TaskName {
        get {
            return this.taskNameField;
        }
        set {
            this.taskNameField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Repository {
        get {
            return this.repositoryField;
        }
        set {
            this.repositoryField = value;
        }
    }
    
    /// <remarks/>
    public string TargetGroupOrUser {
        get {
            return this.targetGroupOrUserField;
        }
        set {
            this.targetGroupOrUserField = value;
        }
    }
    
    /// <remarks/>
    public string CreatedUser {
        get {
            return this.createdUserField;
        }
        set {
            this.createdUserField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime StartTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DueDate {
        get {
            return this.dueDateField;
        }
        set {
            this.dueDateField = value;
        }
    }
    
    /// <remarks/>
    public short Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    public string PercentageComplete {
        get {
            return this.percentageCompleteField;
        }
        set {
            this.percentageCompleteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ScheduledEvent {
    
    private string scheduleNameField;
    
    private string scheduleDescriptionField;
    
    private string repositoryField;
    
    private string targetGroupOrUserField;
    
    private string createdUserField;
    
    private System.DateTime scheduleStartTimeField;
    
    private System.DateTime scheduleEndTimeField;
    
    private System.DateTime scheduleReminderTimeField;
    
    /// <remarks/>
    public string ScheduleName {
        get {
            return this.scheduleNameField;
        }
        set {
            this.scheduleNameField = value;
        }
    }
    
    /// <remarks/>
    public string ScheduleDescription {
        get {
            return this.scheduleDescriptionField;
        }
        set {
            this.scheduleDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Repository {
        get {
            return this.repositoryField;
        }
        set {
            this.repositoryField = value;
        }
    }
    
    /// <remarks/>
    public string TargetGroupOrUser {
        get {
            return this.targetGroupOrUserField;
        }
        set {
            this.targetGroupOrUserField = value;
        }
    }
    
    /// <remarks/>
    public string CreatedUser {
        get {
            return this.createdUserField;
        }
        set {
            this.createdUserField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ScheduleStartTime {
        get {
            return this.scheduleStartTimeField;
        }
        set {
            this.scheduleStartTimeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ScheduleEndTime {
        get {
            return this.scheduleEndTimeField;
        }
        set {
            this.scheduleEndTimeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ScheduleReminderTime {
        get {
            return this.scheduleReminderTimeField;
        }
        set {
            this.scheduleReminderTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void PingServiceCompletedEventHandler(object sender, PingServiceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PingServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal PingServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetContactsCompletedEventHandler(object sender, GetContactsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetContactsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetContactsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Contact[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Contact[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetScheduledEventsCompletedEventHandler(object sender, GetScheduledEventsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetScheduledEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetScheduledEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ScheduledEvent[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ScheduledEvent[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetTasksCompletedEventHandler(object sender, GetTasksCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetTasksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetTasksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Task[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Task[])(this.results[0]));
        }
    }
}
